#!/usr/bin/env bash
# =============================================================================
# setup.sh — Install devco-agent-skills (scope-aware)
# =============================================================================
#
# Detects installation scope automatically:
#
#   USER SCOPE (plugin installed via marketplace/npm — PLUGIN_DIR != PROJECT_ROOT):
#     - CLAUDE.md, rules   → ~/.claude/          (global, every session)
#     - hooks              → ~/.claude/settings.json with ${CLAUDE_PLUGIN_ROOT}
#     - memory             → .claude/memory/     (project scope, always)
#
#   PROJECT SCOPE (plugin repo IS the project — PLUGIN_DIR == PROJECT_ROOT):
#     - CLAUDE.md, rules   → .claude/            (project scope)
#     - hooks              → .claude/settings.json with $CLAUDE_PROJECT_DIR
#     - memory             → .claude/memory/     (project scope)
#
# Usage:
#   bash scripts/setup.sh              # Auto-detect scope
#   bash scripts/setup.sh --update     # Refresh (idempotent re-run)
#
# Safe to re-run: idempotent via start/end markers.
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

MARKER_START="<!-- devco-agent-skills:start -->"
MARKER_END="<!-- devco-agent-skills:end -->"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

ok()   { echo "  ✅  $*"; }
info() { echo "  →   $*"; }
warn() { echo "  ⚠️   $*"; }
h()    { echo ""; echo "── $* ──────────────────────────────────────────"; }

# Inject plugin content into a target file using markers (idempotent)
inject_plugin_content() {
  local target="$1"
  local content_file="$2"

  touch "$target"

  # Remove existing block
  if grep -q "$MARKER_START" "$target" 2>/dev/null; then
    local tmpfile
    tmpfile="$(mktemp)"
    awk "
      /$MARKER_START/ { skip=1 }
      !skip           { print }
      /$MARKER_END/   { skip=0 }
    " "$target" > "$tmpfile"
    mv "$tmpfile" "$target"
    info "Removed previous devco-agent-skills block from $(basename "$target")"
  fi

  # Append fresh block
  {
    printf '\n'
    echo "$MARKER_START"
    echo "<!-- Generated by devco-agent-skills/scripts/setup.sh $(date -u '+%Y-%m-%dT%H:%MZ') -->"
    printf '\n'
    cat "$content_file"
    printf '\n'
    echo "$MARKER_END"
    printf '\n'
  } >> "$target"

  local block_lines
  block_lines="$(awk "/$MARKER_START/{found=1} found{c++} /$MARKER_END/{found=0} END{print c}" "$target")"
  echo "$block_lines"
}

# Write hooks JSON with a given path prefix
write_hooks_json() {
  local target_file="$1"
  local hook_path_prefix="$2"  # e.g., "${CLAUDE_PLUGIN_ROOT}" or "$CLAUDE_PROJECT_DIR"

  cat > "$target_file" <<HOOKJSON
{
  "_comment": "devco-agent-skills-hooks — auto-generated by /setup. Safe to re-run.",
  "extraKnownMarketplaces": {
    "devco-agent-skills": {
      "source": {
        "source": "github",
        "repo": "taipt1504/agent-skills"
      }
    }
  },
  "enabledPlugins": {
    "devco-agent-skills@devco-agent-skills": true
  },
  "hooks": {
    "SessionStart": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${hook_path_prefix}/scripts/hooks/session-start.sh",
            "timeout": 30
          }
        ]
      }
    ],
    "PreToolUse": [
      {
        "matcher": "Edit|Write|MultiEdit",
        "hooks": [
          {
            "type": "command",
            "command": "${hook_path_prefix}/scripts/hooks/suggest-compact.sh",
            "timeout": 5,
            "async": true
          }
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Edit|Write|MultiEdit",
        "hooks": [
          {
            "type": "command",
            "command": "${hook_path_prefix}/scripts/hooks/java-compile-check.sh",
            "timeout": 90
          },
          {
            "type": "command",
            "command": "${hook_path_prefix}/scripts/hooks/java-format.sh",
            "timeout": 60,
            "async": true
          }
        ]
      },
      {
        "hooks": [
          {
            "type": "command",
            "command": "${hook_path_prefix}/skills/continuous-learning-v2/hooks/observe.sh",
            "timeout": 5,
            "async": true
          }
        ]
      }
    ],
    "PreCompact": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${hook_path_prefix}/scripts/hooks/pre-compact.sh",
            "timeout": 30,
            "async": true
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${hook_path_prefix}/scripts/hooks/check-debug-statements.sh",
            "timeout": 15
          },
          {
            "type": "command",
            "command": "${hook_path_prefix}/scripts/hooks/cost-tracker.sh",
            "timeout": 10,
            "async": true
          },
          {
            "type": "command",
            "command": "${hook_path_prefix}/scripts/hooks/session-end.sh",
            "timeout": 60,
            "async": true
          },
          {
            "type": "command",
            "command": "${hook_path_prefix}/scripts/hooks/evaluate-session.sh",
            "timeout": 15,
            "async": true
          }
        ]
      }
    ]
  }
}
HOOKJSON
}

# ---------------------------------------------------------------------------
# Detect scope: user vs project
# ---------------------------------------------------------------------------

PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

if [ "$PROJECT_ROOT" = "$PLUGIN_DIR" ]; then
  SCOPE="project"
  info "Detected: plugin repo IS the project → project scope"
else
  SCOPE="user"
  info "Detected: plugin installed at user scope → global instructions + project memory"
fi

# ---------------------------------------------------------------------------
# SCOPE = user: CLAUDE.md + rules → ~/.claude/ (global)
#               hooks → ~/.claude/settings.json with absolute plugin path
#               memory → .claude/memory/ (project)
# ---------------------------------------------------------------------------

if [ "$SCOPE" = "user" ]; then
  h "User scope: plugin at $PLUGIN_DIR → target project at $PROJECT_ROOT"

  # --- Global: CLAUDE.md → ~/.claude/CLAUDE.md ---
  USER_CLAUDE_DIR="$HOME/.claude"
  USER_CLAUDE_MD="$USER_CLAUDE_DIR/CLAUDE.md"
  mkdir -p "$USER_CLAUDE_DIR"
  lines="$(inject_plugin_content "$USER_CLAUDE_MD" "$PLUGIN_DIR/CLAUDE.md")"
  ok "CLAUDE.md installed globally ($lines lines) → $USER_CLAUDE_MD"

  # --- Global: rules → ~/.claude/rules/ ---
  RULES_SRC="$PLUGIN_DIR/rules"
  RULES_DST="$USER_CLAUDE_DIR/rules"
  if [ -d "$RULES_SRC" ]; then
    mkdir -p "$RULES_DST"
    find "$RULES_SRC" -name "*.md" | while IFS= read -r src_file; do
      rel="${src_file#$RULES_SRC/}"
      dst_file="$RULES_DST/$rel"
      mkdir -p "$(dirname "$dst_file")"
      cp "$src_file" "$dst_file"
    done
    rule_count="$(find "$RULES_DST" -name "*.md" | wc -l | tr -d ' ')"
    ok "$rule_count rule files installed globally → $RULES_DST"
  fi

  # --- Global: hooks → ~/.claude/settings.json with absolute plugin path ---
  SETTINGS_FILE="$USER_CLAUDE_DIR/settings.json"
  HOOKS_MARKER="devco-agent-skills-hooks"

  if [ ! -f "$SETTINGS_FILE" ] || ! grep -q "$HOOKS_MARKER" "$SETTINGS_FILE" 2>/dev/null; then
    # Use absolute path to plugin dir (works even if CLAUDE_PLUGIN_ROOT is not set)
    write_hooks_json "$SETTINGS_FILE" "$PLUGIN_DIR"
    ok "Hook wiring written globally → $SETTINGS_FILE"
    info "Hooks point to plugin at: $PLUGIN_DIR"
  else
    info "Hook wiring already present globally — skipped."
  fi

  # --- Project: memory → .claude/memory/ ---
  CLAUDE_DIR="$PROJECT_ROOT/.claude"
  mkdir -p "$CLAUDE_DIR"

  if [ -f "$PLUGIN_DIR/scripts/memory/init.sh" ]; then
    bash "$PLUGIN_DIR/scripts/memory/init.sh" "$PROJECT_ROOT" 2>/dev/null || true
    ok "Memory directory initialized → $CLAUDE_DIR/memory/"
  fi

  # --- Project: settings.json with marketplace config (for team auto-install) ---
  PROJECT_SETTINGS="$CLAUDE_DIR/settings.json"
  if [ ! -f "$PROJECT_SETTINGS" ] || ! grep -q "extraKnownMarketplaces" "$PROJECT_SETTINGS" 2>/dev/null; then
    cat > "$PROJECT_SETTINGS" <<'TEAMJSON'
{
  "_comment": "devco-agent-skills — team auto-install config. Commit to git.",
  "extraKnownMarketplaces": {
    "devco-agent-skills": {
      "source": {
        "source": "github",
        "repo": "taipt1504/agent-skills"
      }
    }
  },
  "enabledPlugins": {
    "devco-agent-skills@devco-agent-skills": true
  }
}
TEAMJSON
    ok "Team auto-install config → $PROJECT_SETTINGS"
    info "Commit .claude/settings.json so teammates auto-install on clone."
  fi
fi

# ---------------------------------------------------------------------------
# SCOPE = project: everything → .claude/ (project scope)
# ---------------------------------------------------------------------------

if [ "$SCOPE" = "project" ]; then
  h "Project scope: $PROJECT_ROOT"

  CLAUDE_DIR="$PROJECT_ROOT/.claude"
  mkdir -p "$CLAUDE_DIR"

  # --- CLAUDE.md ---
  PROJECT_CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
  if [ -f "$PROJECT_CLAUDE_MD" ]; then
    info "Existing .claude/CLAUDE.md found — injecting plugin rules with markers"
    lines="$(inject_plugin_content "$PROJECT_CLAUDE_MD" "$PLUGIN_DIR/CLAUDE.md")"
    ok "Plugin rules injected into .claude/CLAUDE.md ($lines lines)"
  else
    cp "$PLUGIN_DIR/CLAUDE.md" "$PROJECT_CLAUDE_MD"
    ok ".claude/CLAUDE.md created"
  fi

  # --- WORKING_WORKFLOW.md ---
  WORKFLOW_SRC="$PLUGIN_DIR/WORKING_WORKFLOW.md"
  WORKFLOW_DST="$CLAUDE_DIR/WORKING_WORKFLOW.md"
  if [ -f "$WORKFLOW_SRC" ]; then
    cp "$WORKFLOW_SRC" "$WORKFLOW_DST"
    ok ".claude/WORKING_WORKFLOW.md copied"
  fi

  # --- rules → .claude/rules/ ---
  RULES_SRC="$PLUGIN_DIR/rules"
  RULES_DST="$CLAUDE_DIR/rules"
  if [ -d "$RULES_SRC" ]; then
    mkdir -p "$RULES_DST"
    find "$RULES_SRC" -name "*.md" | while IFS= read -r src_file; do
      rel="${src_file#$RULES_SRC/}"
      dst_file="$RULES_DST/$rel"
      mkdir -p "$(dirname "$dst_file")"
      cp "$src_file" "$dst_file"
    done
    rule_count="$(find "$RULES_DST" -name "*.md" | wc -l | tr -d ' ')"
    ok "$rule_count rule files installed → $RULES_DST"
  fi

  # --- Memory ---
  if [ -f "$PLUGIN_DIR/scripts/memory/init.sh" ]; then
    bash "$PLUGIN_DIR/scripts/memory/init.sh" "$PROJECT_ROOT" 2>/dev/null || true
    ok "Memory directory initialized → $CLAUDE_DIR/memory/"
  fi

  # --- Hooks → .claude/settings.json with $CLAUDE_PROJECT_DIR ---
  SETTINGS_FILE="$CLAUDE_DIR/settings.json"
  HOOKS_MARKER="devco-agent-skills-hooks"

  if [ ! -f "$SETTINGS_FILE" ] || ! grep -q "$HOOKS_MARKER" "$SETTINGS_FILE" 2>/dev/null; then
    write_hooks_json "$SETTINGS_FILE" '$CLAUDE_PROJECT_DIR'
    ok "Hook wiring written → $SETTINGS_FILE"
  else
    info "Hook wiring already present — skipped."
  fi
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

h "Done"
echo ""

if [ "$SCOPE" = "user" ]; then
  echo "  Installed globally (loaded every session, every project):"
  echo "    ~/.claude/CLAUDE.md       — tech stack, workflow, rules"
  echo "    ~/.claude/rules/          — coding rules"
  echo "    ~/.claude/settings.json   — hook wiring (points to plugin)"
  echo ""
  echo "  Installed at project scope:"
  echo "    .claude/settings.json     — team auto-install config"
  echo "    .claude/memory/           — structured session storage"
  echo ""
  echo "  Share with team:"
  echo "    git add .claude/settings.json .claude/memory/"
  echo "    git commit -m 'chore: add Claude Code project context'"
else
  echo "  Installed at project scope (all under .claude/):"
  echo "    .claude/CLAUDE.md           — tech stack, workflow, rules"
  echo "    .claude/WORKING_WORKFLOW.md — 7-phase workflow reference"
  echo "    .claude/rules/              — coding rules"
  echo "    .claude/settings.json       — hook wiring + team config"
  echo "    .claude/memory/             — structured session storage"
  echo ""
  echo "  Share with team:"
  echo "    git add .claude/"
  echo "    git commit -m 'chore: add Claude Code project context'"
fi

echo ""
echo "  Verify: /status"
echo "  Refresh: bash scripts/setup.sh --update"
echo ""
